/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 66
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  sym_identifier = 4,
  sym_name = 5,
  sym_number = 6,
  sym_boolean = 7,
  anon_sym_SLASH_STAR = 8,
  aux_sym_comment_token1 = 9,
  anon_sym_SLASH = 10,
  anon_sym_imports = 11,
  anon_sym_COMMA = 12,
  anon_sym_item = 13,
  anon_sym_EQ = 14,
  sym_item_attribute_text = 15,
  anon_sym_recipe = 16,
  anon_sym_LF_LF = 17,
  anon_sym_SLASH2 = 18,
  anon_sym_COLON = 19,
  sym_module = 20,
  sym_comment = 21,
  sym_imports = 22,
  sym__definition = 23,
  sym_item = 24,
  sym_item_attribute = 25,
  sym__item_attribute_value = 26,
  sym_recipe = 27,
  sym_recipe_requirements = 28,
  sym__recipe_requirement = 29,
  sym_recipe_requirement_choice = 30,
  sym_recipe_requirement_simple = 31,
  sym_recipe_attributes = 32,
  sym_recipe_attribute = 33,
  sym__recipe_attribute_value = 34,
  aux_sym_module_repeat1 = 35,
  aux_sym_imports_repeat1 = 36,
  aux_sym_item_repeat1 = 37,
  aux_sym_recipe_requirements_repeat1 = 38,
  aux_sym_recipe_requirement_choice_repeat1 = 39,
  aux_sym_recipe_attributes_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [sym_name] = "name",
  [sym_number] = "number",
  [sym_boolean] = "boolean",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH] = "/",
  [anon_sym_imports] = "imports",
  [anon_sym_COMMA] = ",",
  [anon_sym_item] = "item",
  [anon_sym_EQ] = "=",
  [sym_item_attribute_text] = "item_attribute_text",
  [anon_sym_recipe] = "recipe",
  [anon_sym_LF_LF] = "\n\n",
  [anon_sym_SLASH2] = "/",
  [anon_sym_COLON] = ":",
  [sym_module] = "module",
  [sym_comment] = "comment",
  [sym_imports] = "imports",
  [sym__definition] = "_definition",
  [sym_item] = "item",
  [sym_item_attribute] = "item_attribute",
  [sym__item_attribute_value] = "_item_attribute_value",
  [sym_recipe] = "recipe",
  [sym_recipe_requirements] = "recipe_requirements",
  [sym__recipe_requirement] = "_recipe_requirement",
  [sym_recipe_requirement_choice] = "recipe_requirement_choice",
  [sym_recipe_requirement_simple] = "recipe_requirement_simple",
  [sym_recipe_attributes] = "recipe_attributes",
  [sym_recipe_attribute] = "recipe_attribute",
  [sym__recipe_attribute_value] = "_recipe_attribute_value",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_imports_repeat1] = "imports_repeat1",
  [aux_sym_item_repeat1] = "item_repeat1",
  [aux_sym_recipe_requirements_repeat1] = "recipe_requirements_repeat1",
  [aux_sym_recipe_requirement_choice_repeat1] = "recipe_requirement_choice_repeat1",
  [aux_sym_recipe_attributes_repeat1] = "recipe_attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [sym_name] = sym_name,
  [sym_number] = sym_number,
  [sym_boolean] = sym_boolean,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_imports] = anon_sym_imports,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_item] = anon_sym_item,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_item_attribute_text] = sym_item_attribute_text,
  [anon_sym_recipe] = anon_sym_recipe,
  [anon_sym_LF_LF] = anon_sym_LF_LF,
  [anon_sym_SLASH2] = anon_sym_SLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_module] = sym_module,
  [sym_comment] = sym_comment,
  [sym_imports] = sym_imports,
  [sym__definition] = sym__definition,
  [sym_item] = sym_item,
  [sym_item_attribute] = sym_item_attribute,
  [sym__item_attribute_value] = sym__item_attribute_value,
  [sym_recipe] = sym_recipe,
  [sym_recipe_requirements] = sym_recipe_requirements,
  [sym__recipe_requirement] = sym__recipe_requirement,
  [sym_recipe_requirement_choice] = sym_recipe_requirement_choice,
  [sym_recipe_requirement_simple] = sym_recipe_requirement_simple,
  [sym_recipe_attributes] = sym_recipe_attributes,
  [sym_recipe_attribute] = sym_recipe_attribute,
  [sym__recipe_attribute_value] = sym__recipe_attribute_value,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_imports_repeat1] = aux_sym_imports_repeat1,
  [aux_sym_item_repeat1] = aux_sym_item_repeat1,
  [aux_sym_recipe_requirements_repeat1] = aux_sym_recipe_requirements_repeat1,
  [aux_sym_recipe_requirement_choice_repeat1] = aux_sym_recipe_requirement_choice_repeat1,
  [aux_sym_recipe_attributes_repeat1] = aux_sym_recipe_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_imports] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_item] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_item_attribute_text] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_recipe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_imports] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_item_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__item_attribute_value] = {
    .visible = false,
    .named = true,
  },
  [sym_recipe] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_requirements] = {
    .visible = true,
    .named = true,
  },
  [sym__recipe_requirement] = {
    .visible = false,
    .named = true,
  },
  [sym_recipe_requirement_choice] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_requirement_simple] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__recipe_attribute_value] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_imports_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_recipe_requirements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_recipe_requirement_choice_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_recipe_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attributes = 1,
  field_key = 2,
  field_label = 3,
  field_name = 4,
  field_requirements = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attributes] = "attributes",
  [field_key] = "key",
  [field_label] = "label",
  [field_name] = "name",
  [field_requirements] = "requirements",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_attributes, 4},
    {field_label, 1},
    {field_requirements, 3},
  [4] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        ',', 59,
        '-', 37,
        '/', 74,
        ':', 75,
        '=', 61,
        'i', 20,
        'm', 22,
        'r', 14,
        '{', 43,
        '}', 44,
        'F', 30,
        'f', 30,
        'T', 33,
        't', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(73);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead == '/') ADVANCE(62);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(63);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(66);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != ',' &&
          lookahead != '-') ADVANCE(71);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(53);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(56);
      if (lookahead == '/') ADVANCE(7);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(56);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(54);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 8:
      if (lookahead == ',') ADVANCE(59);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '/') ADVANCE(74);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 9:
      if (lookahead == ',') ADVANCE(59);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '}') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(57);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(24);
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(60);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(58);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 30:
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 31:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 32:
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 33:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(35);
      END_STATE();
    case 34:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(31);
      END_STATE();
    case 35:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 36:
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 39:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 40:
      if (eof) ADVANCE(41);
      ADVANCE_MAP(
        ',', 59,
        '-', 37,
        '/', 57,
        ':', 75,
        '=', 61,
        'i', 20,
        'm', 22,
        'r', 14,
        '{', 43,
        '}', 44,
        'F', 30,
        'f', 30,
        'T', 33,
        't', 33,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == ' ') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_boolean);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(6);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(6);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(53);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_imports);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_item);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == '*') ADVANCE(55);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == 'A' ||
          lookahead == 'a') ADVANCE(65);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(52);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(67);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(68);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(64);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(64);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(49);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_item_attribute_text);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(36);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_recipe);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LF_LF);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_SLASH2);
      if (lookahead == '*') ADVANCE(53);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 8},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 8},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 8},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 10},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 10},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 5},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_imports] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_item] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_recipe] = ACTIONS(1),
    [anon_sym_SLASH2] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_module] = STATE(42),
    [sym_comment] = STATE(1),
    [anon_sym_module] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 1,
      anon_sym_imports,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_recipe,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      sym_imports,
    STATE(6), 1,
      aux_sym_module_repeat1,
    STATE(16), 1,
      sym__definition,
    STATE(20), 2,
      sym_item,
      sym_recipe,
  [32] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_recipe,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_module_repeat1,
    STATE(16), 1,
      sym__definition,
    STATE(20), 2,
      sym_item,
      sym_recipe,
  [58] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_item,
    ACTIONS(22), 1,
      anon_sym_recipe,
    STATE(16), 1,
      sym__definition,
    STATE(4), 2,
      sym_comment,
      aux_sym_module_repeat1,
    STATE(20), 2,
      sym_item,
      sym_recipe,
  [82] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_recipe,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_module_repeat1,
    STATE(5), 1,
      sym_comment,
    STATE(16), 1,
      sym__definition,
    STATE(20), 2,
      sym_item,
      sym_recipe,
  [108] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_recipe,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_module_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(16), 1,
      sym__definition,
    STATE(20), 2,
      sym_item,
      sym_recipe,
  [134] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(7), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_recipe_requirements_repeat1,
    STATE(11), 1,
      sym_recipe_requirements,
    STATE(31), 1,
      sym__recipe_requirement,
    STATE(34), 2,
      sym_recipe_requirement_choice,
      sym_recipe_requirement_simple,
  [157] = 6,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(32), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(34), 1,
      anon_sym_LF_LF,
    STATE(31), 1,
      sym__recipe_requirement,
    STATE(8), 2,
      sym_comment,
      aux_sym_recipe_requirements_repeat1,
    STATE(34), 2,
      sym_recipe_requirement_choice,
      sym_recipe_requirement_simple,
  [178] = 7,
    ACTIONS(32), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(36), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LF_LF,
    STATE(8), 1,
      aux_sym_recipe_requirements_repeat1,
    STATE(9), 1,
      sym_comment,
    STATE(31), 1,
      sym__recipe_requirement,
    STATE(34), 2,
      sym_recipe_requirement_choice,
      sym_recipe_requirement_simple,
  [201] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    ACTIONS(42), 1,
      sym_identifier,
    STATE(10), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_item_repeat1,
    STATE(40), 1,
      sym_item_attribute,
  [220] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(44), 1,
      sym_identifier,
    STATE(11), 1,
      sym_comment,
    STATE(13), 1,
      aux_sym_recipe_attributes_repeat1,
    STATE(37), 1,
      sym_recipe_attribute,
    STATE(49), 1,
      sym_recipe_attributes,
  [239] = 4,
    ACTIONS(32), 1,
      anon_sym_SLASH_STAR,
    STATE(12), 1,
      sym_comment,
    STATE(55), 1,
      sym__item_attribute_value,
    ACTIONS(46), 3,
      sym_number,
      sym_boolean,
      sym_item_attribute_text,
  [254] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(44), 1,
      sym_identifier,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    STATE(13), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym_recipe_attributes_repeat1,
    STATE(37), 1,
      sym_recipe_attribute,
  [273] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(50), 1,
      anon_sym_RBRACE,
    ACTIONS(52), 1,
      sym_identifier,
    STATE(40), 1,
      sym_item_attribute,
    STATE(14), 2,
      sym_comment,
      aux_sym_item_repeat1,
  [290] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(55), 1,
      anon_sym_RBRACE,
    ACTIONS(57), 1,
      sym_identifier,
    STATE(37), 1,
      sym_recipe_attribute,
    STATE(15), 2,
      sym_comment,
      aux_sym_recipe_attributes_repeat1,
  [307] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(60), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [319] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(17), 1,
      sym_comment,
    ACTIONS(62), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [331] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(64), 1,
      anon_sym_RBRACE,
    ACTIONS(66), 1,
      anon_sym_COMMA,
    STATE(18), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_imports_repeat1,
  [347] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(42), 1,
      sym_identifier,
    STATE(10), 1,
      aux_sym_item_repeat1,
    STATE(19), 1,
      sym_comment,
    STATE(40), 1,
      sym_item_attribute,
  [363] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(68), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [375] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(21), 1,
      sym_comment,
    ACTIONS(70), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [387] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(66), 1,
      anon_sym_COMMA,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(22), 1,
      sym_comment,
    STATE(27), 1,
      aux_sym_imports_repeat1,
  [403] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      anon_sym_SLASH2,
    STATE(23), 1,
      sym_comment,
    STATE(26), 1,
      aux_sym_recipe_requirement_choice_repeat1,
  [419] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(78), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [431] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(25), 1,
      sym_comment,
    ACTIONS(80), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [443] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(76), 1,
      anon_sym_SLASH2,
    ACTIONS(82), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      sym_comment,
    STATE(28), 1,
      aux_sym_recipe_requirement_choice_repeat1,
  [459] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(84), 1,
      anon_sym_RBRACE,
    ACTIONS(86), 1,
      anon_sym_COMMA,
    STATE(27), 2,
      sym_comment,
      aux_sym_imports_repeat1,
  [473] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    ACTIONS(91), 1,
      anon_sym_SLASH2,
    STATE(28), 2,
      sym_comment,
      aux_sym_recipe_requirement_choice_repeat1,
  [487] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    STATE(63), 1,
      sym__recipe_attribute_value,
    ACTIONS(94), 2,
      sym_identifier,
      sym_number,
  [501] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(96), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [513] = 4,
    ACTIONS(32), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(98), 1,
      sym_identifier,
    ACTIONS(100), 1,
      anon_sym_LF_LF,
    STATE(31), 1,
      sym_comment,
  [526] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(102), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [537] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(104), 1,
      anon_sym_RBRACE,
    ACTIONS(106), 1,
      sym_identifier,
    STATE(33), 1,
      sym_comment,
  [550] = 4,
    ACTIONS(32), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(108), 1,
      sym_identifier,
    ACTIONS(110), 1,
      anon_sym_LF_LF,
    STATE(34), 1,
      sym_comment,
  [563] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(84), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [574] = 4,
    ACTIONS(32), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(112), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_LF_LF,
    STATE(36), 1,
      sym_comment,
  [587] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(116), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [598] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(89), 1,
      anon_sym_COMMA,
    ACTIONS(118), 1,
      anon_sym_SLASH2,
    STATE(38), 1,
      sym_comment,
  [611] = 4,
    ACTIONS(32), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(120), 1,
      sym_identifier,
    ACTIONS(122), 1,
      anon_sym_LF_LF,
    STATE(39), 1,
      sym_comment,
  [624] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [635] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(126), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [646] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    STATE(42), 1,
      sym_comment,
  [656] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(130), 1,
      anon_sym_SLASH,
    STATE(43), 1,
      sym_comment,
  [666] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_comment,
  [676] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_comment,
  [686] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 1,
      sym_identifier,
    STATE(46), 1,
      sym_comment,
  [696] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(138), 1,
      sym_identifier,
    STATE(47), 1,
      sym_comment,
  [706] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(140), 1,
      anon_sym_COLON,
    STATE(48), 1,
      sym_comment,
  [716] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_comment,
  [726] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(144), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_comment,
  [736] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(146), 1,
      sym_name,
    STATE(51), 1,
      sym_comment,
  [746] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(148), 1,
      sym_identifier,
    STATE(52), 1,
      sym_comment,
  [756] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
    STATE(53), 1,
      sym_comment,
  [766] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      sym_comment,
  [776] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(154), 1,
      anon_sym_COMMA,
    STATE(55), 1,
      sym_comment,
  [786] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    STATE(56), 1,
      sym_comment,
  [796] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    STATE(57), 1,
      sym_comment,
  [806] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(160), 1,
      sym_identifier,
    STATE(58), 1,
      sym_comment,
  [816] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(162), 1,
      sym_identifier,
    STATE(59), 1,
      sym_comment,
  [826] = 3,
    ACTIONS(32), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(164), 1,
      aux_sym_comment_token1,
    STATE(60), 1,
      sym_comment,
  [836] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(166), 1,
      anon_sym_EQ,
    STATE(61), 1,
      sym_comment,
  [846] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      sym_comment,
  [856] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    STATE(63), 1,
      sym_comment,
  [866] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
    STATE(64), 1,
      sym_comment,
  [876] = 1,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 82,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 134,
  [SMALL_STATE(8)] = 157,
  [SMALL_STATE(9)] = 178,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 220,
  [SMALL_STATE(12)] = 239,
  [SMALL_STATE(13)] = 254,
  [SMALL_STATE(14)] = 273,
  [SMALL_STATE(15)] = 290,
  [SMALL_STATE(16)] = 307,
  [SMALL_STATE(17)] = 319,
  [SMALL_STATE(18)] = 331,
  [SMALL_STATE(19)] = 347,
  [SMALL_STATE(20)] = 363,
  [SMALL_STATE(21)] = 375,
  [SMALL_STATE(22)] = 387,
  [SMALL_STATE(23)] = 403,
  [SMALL_STATE(24)] = 419,
  [SMALL_STATE(25)] = 431,
  [SMALL_STATE(26)] = 443,
  [SMALL_STATE(27)] = 459,
  [SMALL_STATE(28)] = 473,
  [SMALL_STATE(29)] = 487,
  [SMALL_STATE(30)] = 501,
  [SMALL_STATE(31)] = 513,
  [SMALL_STATE(32)] = 526,
  [SMALL_STATE(33)] = 537,
  [SMALL_STATE(34)] = 550,
  [SMALL_STATE(35)] = 563,
  [SMALL_STATE(36)] = 574,
  [SMALL_STATE(37)] = 587,
  [SMALL_STATE(38)] = 598,
  [SMALL_STATE(39)] = 611,
  [SMALL_STATE(40)] = 624,
  [SMALL_STATE(41)] = 635,
  [SMALL_STATE(42)] = 646,
  [SMALL_STATE(43)] = 656,
  [SMALL_STATE(44)] = 666,
  [SMALL_STATE(45)] = 676,
  [SMALL_STATE(46)] = 686,
  [SMALL_STATE(47)] = 696,
  [SMALL_STATE(48)] = 706,
  [SMALL_STATE(49)] = 716,
  [SMALL_STATE(50)] = 726,
  [SMALL_STATE(51)] = 736,
  [SMALL_STATE(52)] = 746,
  [SMALL_STATE(53)] = 756,
  [SMALL_STATE(54)] = 766,
  [SMALL_STATE(55)] = 776,
  [SMALL_STATE(56)] = 786,
  [SMALL_STATE(57)] = 796,
  [SMALL_STATE(58)] = 806,
  [SMALL_STATE(59)] = 816,
  [SMALL_STATE(60)] = 826,
  [SMALL_STATE(61)] = 836,
  [SMALL_STATE(62)] = 846,
  [SMALL_STATE(63)] = 856,
  [SMALL_STATE(64)] = 866,
  [SMALL_STATE(65)] = 876,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_recipe_requirements_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [32] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_requirements_repeat1, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_attributes, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_attributes_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_recipe_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imports, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imports, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 5, 0, 1),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imports, 5, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_imports_repeat1, 2, 0, 0),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_imports_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_requirement_choice_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_recipe_requirement_choice_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 6, 0, 2),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_recipe_requirements_repeat1, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_requirements_repeat1, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_attribute, 4, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__recipe_requirement, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__recipe_requirement, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_recipe_requirement_simple, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_requirement_simple, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_attributes_repeat1, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_recipe_requirement_choice_repeat1, 2, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_recipe_requirement_choice, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_requirement_choice, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_attribute, 4, 0, 3),
  [128] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_requirements, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 6, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__item_attribute_value, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 5, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__recipe_attribute_value, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 4, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pz_scripts(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pz_scripts",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
