/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_module = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  sym_identifier = 4,
  sym_name = 5,
  sym_number = 6,
  anon_sym_SLASH_STAR = 7,
  aux_sym_comment_token1 = 8,
  anon_sym_SLASH = 9,
  anon_sym_imports = 10,
  anon_sym_COMMA = 11,
  anon_sym_item = 12,
  anon_sym_EQ = 13,
  sym_item_attribute_value = 14,
  anon_sym_recipe = 15,
  anon_sym_LF_LF = 16,
  anon_sym_SLASH2 = 17,
  anon_sym_COLON = 18,
  sym_module = 19,
  sym_comment = 20,
  sym_imports = 21,
  sym__definition = 22,
  sym_item = 23,
  sym_item_attribute = 24,
  sym_recipe = 25,
  sym_recipe_requirements = 26,
  sym__recipe_requirement = 27,
  sym_recipe_requirement_choice = 28,
  sym_recipe_requirement_simple = 29,
  sym_recipe_attributes = 30,
  sym_recipe_attribute = 31,
  sym__recipe_attribute_value = 32,
  aux_sym_module_repeat1 = 33,
  aux_sym_imports_repeat1 = 34,
  aux_sym_item_repeat1 = 35,
  aux_sym_recipe_requirements_repeat1 = 36,
  aux_sym_recipe_requirement_choice_repeat1 = 37,
  aux_sym_recipe_attributes_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_module] = "module",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_identifier] = "identifier",
  [sym_name] = "name",
  [sym_number] = "number",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH] = "/",
  [anon_sym_imports] = "imports",
  [anon_sym_COMMA] = ",",
  [anon_sym_item] = "item",
  [anon_sym_EQ] = "=",
  [sym_item_attribute_value] = "item_attribute_value",
  [anon_sym_recipe] = "recipe",
  [anon_sym_LF_LF] = "\n\n",
  [anon_sym_SLASH2] = "/",
  [anon_sym_COLON] = ":",
  [sym_module] = "module",
  [sym_comment] = "comment",
  [sym_imports] = "imports",
  [sym__definition] = "_definition",
  [sym_item] = "item",
  [sym_item_attribute] = "item_attribute",
  [sym_recipe] = "recipe",
  [sym_recipe_requirements] = "recipe_requirements",
  [sym__recipe_requirement] = "_recipe_requirement",
  [sym_recipe_requirement_choice] = "recipe_requirement_choice",
  [sym_recipe_requirement_simple] = "recipe_requirement_simple",
  [sym_recipe_attributes] = "recipe_attributes",
  [sym_recipe_attribute] = "recipe_attribute",
  [sym__recipe_attribute_value] = "_recipe_attribute_value",
  [aux_sym_module_repeat1] = "module_repeat1",
  [aux_sym_imports_repeat1] = "imports_repeat1",
  [aux_sym_item_repeat1] = "item_repeat1",
  [aux_sym_recipe_requirements_repeat1] = "recipe_requirements_repeat1",
  [aux_sym_recipe_requirement_choice_repeat1] = "recipe_requirement_choice_repeat1",
  [aux_sym_recipe_attributes_repeat1] = "recipe_attributes_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_identifier] = sym_identifier,
  [sym_name] = sym_name,
  [sym_number] = sym_number,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_imports] = anon_sym_imports,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_item] = anon_sym_item,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_item_attribute_value] = sym_item_attribute_value,
  [anon_sym_recipe] = anon_sym_recipe,
  [anon_sym_LF_LF] = anon_sym_LF_LF,
  [anon_sym_SLASH2] = anon_sym_SLASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_module] = sym_module,
  [sym_comment] = sym_comment,
  [sym_imports] = sym_imports,
  [sym__definition] = sym__definition,
  [sym_item] = sym_item,
  [sym_item_attribute] = sym_item_attribute,
  [sym_recipe] = sym_recipe,
  [sym_recipe_requirements] = sym_recipe_requirements,
  [sym__recipe_requirement] = sym__recipe_requirement,
  [sym_recipe_requirement_choice] = sym_recipe_requirement_choice,
  [sym_recipe_requirement_simple] = sym_recipe_requirement_simple,
  [sym_recipe_attributes] = sym_recipe_attributes,
  [sym_recipe_attribute] = sym_recipe_attribute,
  [sym__recipe_attribute_value] = sym__recipe_attribute_value,
  [aux_sym_module_repeat1] = aux_sym_module_repeat1,
  [aux_sym_imports_repeat1] = aux_sym_imports_repeat1,
  [aux_sym_item_repeat1] = aux_sym_item_repeat1,
  [aux_sym_recipe_requirements_repeat1] = aux_sym_recipe_requirements_repeat1,
  [aux_sym_recipe_requirement_choice_repeat1] = aux_sym_recipe_requirement_choice_repeat1,
  [aux_sym_recipe_attributes_repeat1] = aux_sym_recipe_attributes_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_imports] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_item] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_item_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_recipe] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_module] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_imports] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_item] = {
    .visible = true,
    .named = true,
  },
  [sym_item_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_requirements] = {
    .visible = true,
    .named = true,
  },
  [sym__recipe_requirement] = {
    .visible = false,
    .named = true,
  },
  [sym_recipe_requirement_choice] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_requirement_simple] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_attributes] = {
    .visible = true,
    .named = true,
  },
  [sym_recipe_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__recipe_attribute_value] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_imports_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_item_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_recipe_requirements_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_recipe_requirement_choice_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_recipe_attributes_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_attributes = 1,
  field_key = 2,
  field_label = 3,
  field_name = 4,
  field_requirements = 5,
  field_value = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_attributes] = "attributes",
  [field_key] = "key",
  [field_label] = "label",
  [field_name] = "name",
  [field_requirements] = "requirements",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 3},
  [3] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_attributes, 4},
    {field_label, 1},
    {field_requirements, 3},
  [4] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        ',', 46,
        '/', 52,
        ':', 53,
        '=', 48,
        'i', 20,
        'm', 22,
        'r', 14,
        '{', 35,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(43);
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(42);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 8:
      if (lookahead == ',') ADVANCE(46);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '}') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == '/') ADVANCE(44);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(24);
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'm') ADVANCE(47);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(13);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 31:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 32:
      if (eof) ADVANCE(33);
      ADVANCE_MAP(
        ',', 46,
        '/', 44,
        ':', 53,
        '=', 48,
        'i', 20,
        'm', 22,
        'r', 14,
        '{', 35,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == ' ') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(41);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_imports);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_item);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_item_attribute_value);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_recipe);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LF_LF);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SLASH2);
      if (lookahead == '*') ADVANCE(41);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 7},
  [11] = {.lex_state = 7},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 7},
  [14] = {.lex_state = 7},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 7},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 7},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 7},
  [40] = {.lex_state = 7},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 7},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 11},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 9},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 7},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_imports] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_item] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_recipe] = ACTIONS(1),
    [anon_sym_SLASH2] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_module] = STATE(60),
    [sym_comment] = STATE(1),
    [anon_sym_module] = ACTIONS(5),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    ACTIONS(9), 1,
      anon_sym_imports,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_recipe,
    STATE(2), 1,
      sym_comment,
    STATE(3), 1,
      sym_imports,
    STATE(6), 1,
      aux_sym_module_repeat1,
    STATE(15), 1,
      sym__definition,
    STATE(19), 2,
      sym_item,
      sym_recipe,
  [32] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_recipe,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      sym_comment,
    STATE(5), 1,
      aux_sym_module_repeat1,
    STATE(15), 1,
      sym__definition,
    STATE(19), 2,
      sym_item,
      sym_recipe,
  [58] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_item,
    ACTIONS(22), 1,
      anon_sym_recipe,
    STATE(15), 1,
      sym__definition,
    STATE(4), 2,
      sym_comment,
      aux_sym_module_repeat1,
    STATE(19), 2,
      sym_item,
      sym_recipe,
  [82] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_recipe,
    ACTIONS(25), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_module_repeat1,
    STATE(5), 1,
      sym_comment,
    STATE(15), 1,
      sym__definition,
    STATE(19), 2,
      sym_item,
      sym_recipe,
  [108] = 8,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(11), 1,
      anon_sym_item,
    ACTIONS(13), 1,
      anon_sym_recipe,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_module_repeat1,
    STATE(6), 1,
      sym_comment,
    STATE(15), 1,
      sym__definition,
    STATE(19), 2,
      sym_item,
      sym_recipe,
  [134] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(7), 1,
      sym_comment,
    STATE(8), 1,
      aux_sym_recipe_requirements_repeat1,
    STATE(13), 1,
      sym_recipe_requirements,
    STATE(30), 1,
      sym__recipe_requirement,
    STATE(33), 2,
      sym_recipe_requirement_choice,
      sym_recipe_requirement_simple,
  [157] = 7,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(33), 1,
      anon_sym_LF_LF,
    STATE(8), 1,
      sym_comment,
    STATE(9), 1,
      aux_sym_recipe_requirements_repeat1,
    STATE(30), 1,
      sym__recipe_requirement,
    STATE(33), 2,
      sym_recipe_requirement_choice,
      sym_recipe_requirement_simple,
  [180] = 6,
    ACTIONS(31), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(38), 1,
      anon_sym_LF_LF,
    STATE(30), 1,
      sym__recipe_requirement,
    STATE(9), 2,
      sym_comment,
      aux_sym_recipe_requirements_repeat1,
    STATE(33), 2,
      sym_recipe_requirement_choice,
      sym_recipe_requirement_simple,
  [201] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(40), 1,
      anon_sym_RBRACE,
    ACTIONS(42), 1,
      sym_identifier,
    STATE(10), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_item_repeat1,
    STATE(31), 1,
      sym_item_attribute,
  [220] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(44), 1,
      anon_sym_RBRACE,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(11), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_recipe_attributes_repeat1,
    STATE(36), 1,
      sym_recipe_attribute,
  [239] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(48), 1,
      anon_sym_RBRACE,
    ACTIONS(50), 1,
      sym_identifier,
    STATE(31), 1,
      sym_item_attribute,
    STATE(12), 2,
      sym_comment,
      aux_sym_item_repeat1,
  [256] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(46), 1,
      sym_identifier,
    STATE(11), 1,
      aux_sym_recipe_attributes_repeat1,
    STATE(13), 1,
      sym_comment,
    STATE(36), 1,
      sym_recipe_attribute,
    STATE(49), 1,
      sym_recipe_attributes,
  [275] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(55), 1,
      sym_identifier,
    STATE(36), 1,
      sym_recipe_attribute,
    STATE(14), 2,
      sym_comment,
      aux_sym_recipe_attributes_repeat1,
  [292] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(15), 1,
      sym_comment,
    ACTIONS(58), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [304] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(16), 1,
      sym_comment,
    ACTIONS(60), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [316] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(62), 1,
      anon_sym_RBRACE,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    STATE(17), 1,
      sym_comment,
    STATE(21), 1,
      aux_sym_imports_repeat1,
  [332] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(42), 1,
      sym_identifier,
    STATE(10), 1,
      aux_sym_item_repeat1,
    STATE(18), 1,
      sym_comment,
    STATE(31), 1,
      sym_item_attribute,
  [348] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(19), 1,
      sym_comment,
    ACTIONS(66), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [360] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(20), 1,
      sym_comment,
    ACTIONS(68), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [372] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    ACTIONS(70), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym_imports_repeat1,
  [388] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(22), 1,
      sym_comment,
    ACTIONS(72), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [400] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      anon_sym_SLASH2,
    STATE(23), 1,
      sym_comment,
    STATE(26), 1,
      aux_sym_recipe_requirement_choice_repeat1,
  [416] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(24), 1,
      sym_comment,
    ACTIONS(78), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [428] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    ACTIONS(82), 1,
      anon_sym_COMMA,
    STATE(25), 2,
      sym_comment,
      aux_sym_imports_repeat1,
  [442] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(76), 1,
      anon_sym_SLASH2,
    ACTIONS(85), 1,
      anon_sym_COMMA,
    STATE(26), 1,
      sym_comment,
    STATE(27), 1,
      aux_sym_recipe_requirement_choice_repeat1,
  [458] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(89), 1,
      anon_sym_SLASH2,
    STATE(27), 2,
      sym_comment,
      aux_sym_recipe_requirement_choice_repeat1,
  [472] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_comment,
    STATE(63), 1,
      sym__recipe_attribute_value,
    ACTIONS(92), 2,
      sym_identifier,
      sym_number,
  [486] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(94), 3,
      anon_sym_RBRACE,
      anon_sym_item,
      anon_sym_recipe,
  [498] = 4,
    ACTIONS(31), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(96), 1,
      sym_identifier,
    ACTIONS(98), 1,
      anon_sym_LF_LF,
    STATE(30), 1,
      sym_comment,
  [511] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(100), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [522] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(102), 1,
      anon_sym_RBRACE,
    ACTIONS(104), 1,
      sym_identifier,
    STATE(32), 1,
      sym_comment,
  [535] = 4,
    ACTIONS(31), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(106), 1,
      sym_identifier,
    ACTIONS(108), 1,
      anon_sym_LF_LF,
    STATE(33), 1,
      sym_comment,
  [548] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(80), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [559] = 4,
    ACTIONS(31), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(110), 1,
      sym_identifier,
    ACTIONS(112), 1,
      anon_sym_LF_LF,
    STATE(35), 1,
      sym_comment,
  [572] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(114), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [583] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(87), 1,
      anon_sym_COMMA,
    ACTIONS(116), 1,
      anon_sym_SLASH2,
    STATE(37), 1,
      sym_comment,
  [596] = 4,
    ACTIONS(31), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(120), 1,
      anon_sym_LF_LF,
    STATE(38), 1,
      sym_comment,
  [609] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(122), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [620] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(124), 2,
      anon_sym_RBRACE,
      sym_identifier,
  [631] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(41), 1,
      sym_comment,
  [641] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(128), 1,
      sym_item_attribute_value,
    STATE(42), 1,
      sym_comment,
  [651] = 3,
    ACTIONS(31), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(130), 1,
      aux_sym_comment_token1,
    STATE(43), 1,
      sym_comment,
  [661] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
    STATE(44), 1,
      sym_comment,
  [671] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_comment,
  [681] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(136), 1,
      sym_identifier,
    STATE(46), 1,
      sym_comment,
  [691] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(138), 1,
      anon_sym_EQ,
    STATE(47), 1,
      sym_comment,
  [701] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(140), 1,
      anon_sym_COLON,
    STATE(48), 1,
      sym_comment,
  [711] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(142), 1,
      anon_sym_RBRACE,
    STATE(49), 1,
      sym_comment,
  [721] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(144), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      sym_comment,
  [731] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(146), 1,
      sym_identifier,
    STATE(51), 1,
      sym_comment,
  [741] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(148), 1,
      sym_identifier,
    STATE(52), 1,
      sym_comment,
  [751] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(150), 1,
      sym_name,
    STATE(53), 1,
      sym_comment,
  [761] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(152), 1,
      anon_sym_COMMA,
    STATE(54), 1,
      sym_comment,
  [771] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
    STATE(55), 1,
      sym_comment,
  [781] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(156), 1,
      anon_sym_SLASH,
    STATE(56), 1,
      sym_comment,
  [791] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(158), 1,
      ts_builtin_sym_end,
    STATE(57), 1,
      sym_comment,
  [801] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(160), 1,
      sym_identifier,
    STATE(58), 1,
      sym_comment,
  [811] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(162), 1,
      sym_identifier,
    STATE(59), 1,
      sym_comment,
  [821] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(164), 1,
      ts_builtin_sym_end,
    STATE(60), 1,
      sym_comment,
  [831] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
    STATE(61), 1,
      sym_comment,
  [841] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(168), 1,
      anon_sym_COMMA,
    STATE(62), 1,
      sym_comment,
  [851] = 3,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(170), 1,
      anon_sym_COMMA,
    STATE(63), 1,
      sym_comment,
  [861] = 1,
    ACTIONS(172), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 82,
  [SMALL_STATE(6)] = 108,
  [SMALL_STATE(7)] = 134,
  [SMALL_STATE(8)] = 157,
  [SMALL_STATE(9)] = 180,
  [SMALL_STATE(10)] = 201,
  [SMALL_STATE(11)] = 220,
  [SMALL_STATE(12)] = 239,
  [SMALL_STATE(13)] = 256,
  [SMALL_STATE(14)] = 275,
  [SMALL_STATE(15)] = 292,
  [SMALL_STATE(16)] = 304,
  [SMALL_STATE(17)] = 316,
  [SMALL_STATE(18)] = 332,
  [SMALL_STATE(19)] = 348,
  [SMALL_STATE(20)] = 360,
  [SMALL_STATE(21)] = 372,
  [SMALL_STATE(22)] = 388,
  [SMALL_STATE(23)] = 400,
  [SMALL_STATE(24)] = 416,
  [SMALL_STATE(25)] = 428,
  [SMALL_STATE(26)] = 442,
  [SMALL_STATE(27)] = 458,
  [SMALL_STATE(28)] = 472,
  [SMALL_STATE(29)] = 486,
  [SMALL_STATE(30)] = 498,
  [SMALL_STATE(31)] = 511,
  [SMALL_STATE(32)] = 522,
  [SMALL_STATE(33)] = 535,
  [SMALL_STATE(34)] = 548,
  [SMALL_STATE(35)] = 559,
  [SMALL_STATE(36)] = 572,
  [SMALL_STATE(37)] = 583,
  [SMALL_STATE(38)] = 596,
  [SMALL_STATE(39)] = 609,
  [SMALL_STATE(40)] = 620,
  [SMALL_STATE(41)] = 631,
  [SMALL_STATE(42)] = 641,
  [SMALL_STATE(43)] = 651,
  [SMALL_STATE(44)] = 661,
  [SMALL_STATE(45)] = 671,
  [SMALL_STATE(46)] = 681,
  [SMALL_STATE(47)] = 691,
  [SMALL_STATE(48)] = 701,
  [SMALL_STATE(49)] = 711,
  [SMALL_STATE(50)] = 721,
  [SMALL_STATE(51)] = 731,
  [SMALL_STATE(52)] = 741,
  [SMALL_STATE(53)] = 751,
  [SMALL_STATE(54)] = 761,
  [SMALL_STATE(55)] = 771,
  [SMALL_STATE(56)] = 781,
  [SMALL_STATE(57)] = 791,
  [SMALL_STATE(58)] = 801,
  [SMALL_STATE(59)] = 811,
  [SMALL_STATE(60)] = 821,
  [SMALL_STATE(61)] = 831,
  [SMALL_STATE(62)] = 841,
  [SMALL_STATE(63)] = 851,
  [SMALL_STATE(64)] = 861,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_recipe_requirements_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_requirements_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_attributes, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 2, 0, 0),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_attributes_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_recipe_attributes_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_module_repeat1, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imports, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imports, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item, 5, 0, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imports, 5, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_imports_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_imports_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_requirement_choice_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_recipe_requirement_choice_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe, 6, 0, 2),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_recipe_requirements_repeat1, 1, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_requirements_repeat1, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_item_repeat1, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__recipe_requirement, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__recipe_requirement, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_recipe_requirement_simple, 2, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_requirement_simple, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_recipe_attributes_repeat1, 1, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_recipe_requirement_choice_repeat1, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_recipe_requirement_choice, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_requirement_choice, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_item_attribute, 4, 0, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_attribute, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_recipe_requirements, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [156] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 6, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [164] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module, 5, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__recipe_attribute_value, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pz_scripts(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pz_scripts",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
